baseURL: https://lieskjur.github.io/Notes-native
languageCode: en-us
title: Notes

theme: hugo-book

params:
  # BookTheme : "auto" # light(default)/dark/auto
  BookRepo: https://github.com/lieskjur/Notes
  BookEditPath: edit/main/
  BookDateFormat: "January 2, 2006"